import "unknwn.idl";
[
	object,
	uuid(2E0F96FD-E25A-4820-91F1-9D3DF3B639D3),
	helpstring("IMyMath Interface"),
	pointer_default(unique),
	dual,
	oleautomation
]
interface IMyMath : IDispatch
{
	import "oaidl.idl";
	HRESULT __stdcall SumOfTwoIntegers([in]int, [in]int, [out, retval]int *);
	HRESULT __stdcall SubtractionOfTwoIntegers([in]int, [in]int, [out, retval]int *);
};
[
	uuid(1523BC6C-CE5F-4183-8260-CCC59234D79E),
	version(1.0),
	helpstring("MyMath Component's Type Library")
]
library AutomationServerTypeLib
{
	importlib("stdole32.tlb");
	[
		uuid(F8506914-3E4C-4665-BB4B-689F559E7480),
		helpstring("Mat Automation Component Class")
	]
	coclass CMyMath
	{
		[default]interface IMyMath;
	};
};
